### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by NP-Hardass** [virtualsquare/vde-2#18]
Hi,

Since Python 2 has been sunset as of Jan 1, 2020 (https://www.python.org/doc/sunset-python-2/), I was wondering if there were plans to update the bindings to support Python 3.

Thanks.

**Comment by danielinux** [comment]
hello @NP-Hardass - not sure if you are still interested in python bindings. We have removed the obsolete python-2 support, feel free to reopen if you think we should introduce python bindings in the new vde-4 plugs.
