### ISSUE TITLE
vde_crypcab does not compile against libssl1.1

### ISSUE THREAD

**Issue by rd235** [virtualsquare/vde-2#2]
This is the error:
cryptcab.c:25:23: error: storage size of ‘ctx’ isn’t known
 static EVP_CIPHER_CTX ctx
                       ^~~

**Comment by danielinux** [comment]
OK, I removed the dependency on OpenSSL completely in 8599321526d0a31925fe55cabbe132b752cb268a. 
The cipher we were using is a bit outdated, the IV were not being rotated correctly and the integrity of the incoming packet was not checked correctly, so I refactored the crypto part and now we are using @wolfSSL instead.
