### ISSUE TITLE
Missing vde_router

### ISSUE THREAD

**Issue by Cesarsk** [virtualsquare/vde-2#21]
Vde_router is absent , why ? I can't use Virtualbricks without it. Is there a way to restore it ?

**Comment by danielinux** [comment]
Hi, vde_router has never been part of vde-2. There is a layer-3 switch with traffic control (vde_l3) that can be used instead. Router support in virtualbricks is not present (if you try to add a "router" object, it will not be configurable nor usable).

**Comment by danielinux** [comment]
Hey

**Comment by danielinux** [comment]
@Cesarsk Sorry I made some confusion about the modules.. vde_router is still there, it's only excluded from the debian package, but you can still install it from the sources. I don't think there is support in virtualbricks for vde_router anyway, but I might be running an older version.

Thanks,
