### ISSUE TITLE
Request: new release

### ISSUE THREAD

**Issue by AkihiroSuda** [virtualsquare/vde-2#26]
The latest release v2.3.2 was nearly 10 years ago: https://sourceforge.net/projects/vde/files/vde2/2.3.2/

@rd235 @danielinux 
Could you consider creating a new release from the current master?

(I know [vdeplug4](https://github.com/rd235/vdeplug4) is the successor of this project, but [homebrew package of QEMU still depends on VDE2](https://github.com/Homebrew/homebrew-core/blob/master/Formula/vde.rb), and my ["vde_vmnet"](https://github.com/AkihiroSuda/vde_vmnet) requires `vde_switch` of VDE2)

**Comment by AkihiroSuda** [comment]
@danielinux Do you have a plan for this? 🙏

**Comment by danielinux** [comment]
We discussed about this with @rd235. We are fixing a few things and prepare a new release. This will probably be the last vde-2 release, as we are working on migrating all the tools to vde-4 and provide backwards-compatible command line options for (almost) everything.

Thanks!

**Comment by AkihiroSuda** [comment]
Thank you!

> This will probably be the last vde-2 release, as we are working on migrating all the tools to vde-4 and provide backwards-compatible command line options for (almost) everything.

Will vde-4 support macOS too?

**Comment by danielinux** [comment]
> Will vde-4 support macOS too?

The fact is that neither @rd235 nor I have a macOS system to develop/test on. We would welcome all contributions on vde-4 to make it work on macOS. Meanwhile we'll keep maintaining vde-2 so that you don't have any discontinuity on homebrew and similar projects.

**Comment by dvzrv** [comment]
Hi! I'm packaging vde2 for Arch Linux.

Would it be possible for you to tag a new release of this project? This would be really great, as so much has changed over time and e.g. building against openssl 1.1.x is not possible with 2.3.2 out of the box. This would help downstreams a great deal to integrate this project with qemu until you figure out the way forward with vdeplug4.

Thanks!

**Comment by dvzrv** [comment]
@danielinux Hi, any news on this? :)

**Comment by danielinux** [comment]
Done! Thanks for waiting!
